name: test
on: [push]
defaults:
  run:
    working-directory: 'dje123'
jobs:
  test-out-command:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'dje123'

      # - name: Check brew version
      #   run: "brew --version"

      # - name: Check brew installations
      #   run: |
      #     brew list
      #     brew deps --tree --installed

      - name: Path?
        run: echo $PATH

      - name: PWD
        run: pwd