name: test
on: [push]
jobs:
  test-out-command:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check brew version
        run: "brew --version"

      - name: Check brew installations
        run: |
          brew list
          brew deps --tree --installed

      - name: Path?
        run: echo $PATH
